server:
  port: 8060
spring:
  security:
    user:
      password: ${PAYROLL_API_PASS}
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: ${PAYROLL_GITHUB_CLIENTID}
#            clientSecret: ${PAYROLL_GITHUB_CLIENT_SECRET}
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - user:email
#              - read:user
#        provider:
#          github:
#            userInfoUri: https://api.github.com/user
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
