###
GET http://localhost:8060

###
GET http://localhost:8060/csrf-token
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8060/employees/2
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8060/employees/2

###
GET http://localhost:8060/employees
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8060/employees?withoutDismissed=true
Authorization: Basic dXNlcjpwYXNzd29yZA==

### Add
POST http://localhost:8060/employees
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==
X-Csrf-Token: 3549e7b1-8c97-48c1-9056-a818a564be34

{
  "name": "Til Wol",
  "role": "manager"
}

<> 2024-01-10T074831.201.json

### Hire
PUT http://localhost:8060/employees/3
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

<> 2024-01-10T074835.200.json
<> 2024-01-10T074529.200.json
<> 2024-01-10T074459.200.json
<> 2024-01-10T074433.200.json


### Update
PATCH http://localhost:8060/employees/3
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "name": "Til Wol",
  "role": "janitor"
}

<> 2024-01-10T074840.201.json
<> 2024-01-10T074728.201.json
<> 2024-01-10T074515.201.json
<> 2024-01-10T074441.201.json


### Dismiss
DELETE http://localhost:8060/employees/4
Authorization: Basic dXNlcjpwYXNzd29yZA==

<> 2024-01-10T074532.200.json

